### ISSUE TITLE
Can you share a working xformers conda setup?

### ISSUE THREAD

**Issue by andreemic** [salesforce/HIVE#3]
Hey, for me the conda environment in this repo doesn't resolve upon adding xformers via conda. 
Adding xformers via pip seems to break something about PyTorch/CUDA compat which leads to some tensors being on the wrong device at runtime (does _not_ happen without xformers installation).

I used the installation procedures from the [xformers Readme](https://github.com/facebookresearch/xformers).

I assume you used xformers for training so let me know if you can share a working setup.

**Comment by shugerdou** [comment]
@andreemic We did not use xformers in this experiment. We welcome pull requests by updating xformers config. Thanks.

**Comment by andreemic** [comment]
Thanks for your quick answer! 

I'll try to get a working setup and PR if I have a solution.
