### ISSUE TITLE
where is the reward model ckpt?

### ISSUE THREAD

**Issue by youngfly11** [salesforce/HIVE#4]
hi, thanks for your great work. 
Is there any planning to release the reward model checkpoint (blip model)?

**Comment by yihaocs** [comment]
Hi Yongfei,

Thanks for your interest! I will release the checkpoint of the reward model and the training dataset \ code soon. Sorry that we are busy with the NeurIPS.

**Comment by youngfly11** [comment]
Is there any further update?

**Comment by shugerdou** [comment]
@youngfly11  We are busy with some deadlines. Will release it in about a week. Thanks for your interest.

**Comment by shugerdou** [comment]
Sorry that we are delayed in releasing due to some other projects. Keep tuned and it should be released soon!
